---
- name: copy httpd.conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  notify: reload httpd
- name: copy ports.conf
  template:
    src: ports.conf.j2
    dest: /etc/httpd/conf.d/ports.conf
    owner: root
    group: root
    mode: 0644
  notify: reload httpd
- name: create www dirs
  file:
    path: /var/www/ports_{{item}}
    state: directory
    owner: root
    group: root
  notify: reload httpd
  with_items: "{{httpd_whoami_ports}}"
- name: create index.html for ports
  template:
    src: www/index.html.j2
    dest: /var/www/ports_{{item}}/index.html
    owner: root
    group: root
    mode: 0644
  with_items: "{{httpd_whoami_ports}}"
  notify: reload httpd
